/**
 * Curated list of common ARK creatures with their DinoNameTag (for spawn-weight
 * tuning) and class name (for spawn replacements). Not exhaustive — the creature
 * picker also accepts a custom tag/class for anything not listed (incl. mods).
 */
export interface ArkCreature {
  name: string;
  tag: string;
  className: string;
}

export const ARK_CREATURES: ArkCreature[] = [
  { name: "Rex", tag: "Rex", className: "Rex_Character_BP_C" },
  { name: "Giganotosaurus", tag: "Gigant", className: "Gigant_Character_BP_C" },
  { name: "Raptor", tag: "Raptor", className: "Raptor_Character_BP_C" },
  { name: "Carnotaurus", tag: "Carno", className: "Carno_Character_BP_C" },
  { name: "Spinosaur", tag: "Spino", className: "Spino_Character_BP_C" },
  { name: "Allosaurus", tag: "Allo", className: "Allo_Character_BP_C" },
  { name: "Therizinosaur", tag: "Therizino", className: "Therizino_Character_BP_C" },
  { name: "Brontosaurus", tag: "Bronto", className: "Bronto_Character_BP_C" },
  { name: "Triceratops", tag: "Trike", className: "Trike_Character_BP_C" },
  { name: "Stegosaurus", tag: "Stego", className: "Stego_Character_BP_C" },
  { name: "Parasaur", tag: "Para", className: "Para_Character_BP_C" },
  { name: "Ankylosaurus", tag: "Ankylo", className: "Ankylo_Character_BP_C" },
  { name: "Doedicurus", tag: "Doed", className: "Doed_Character_BP_C" },
  { name: "Diplodocus", tag: "Diplodocus", className: "Diplodocus_Character_BP_C" },
  { name: "Pteranodon", tag: "Ptero", className: "Ptero_Character_BP_C" },
  { name: "Argentavis", tag: "Argent", className: "Argent_Character_BP_C" },
  { name: "Quetzal", tag: "Quetz", className: "Quetz_Character_BP_C" },
  { name: "Tapejara", tag: "Tapejara", className: "Tapejara_Character_BP_C" },
  { name: "Pelagornis", tag: "Pela", className: "Pela_Character_BP_C" },
  { name: "Ichthyornis", tag: "Ichthyornis", className: "Ichthyornis_Character_BP_C" },
  { name: "Dimorphodon", tag: "Dimorph", className: "Dimorph_Character_BP_C" },
  { name: "Megalodon", tag: "Megalodon", className: "Megalodon_Character_BP_C" },
  { name: "Mosasaurus", tag: "Mosa", className: "Mosa_Character_BP_C" },
  { name: "Plesiosaur", tag: "Plesi", className: "Plesi_Character_BP_C" },
  { name: "Ichthyosaurus", tag: "Dolphin", className: "Dolphin_Character_BP_C" },
  { name: "Sarcosuchus", tag: "Sarco", className: "Sarco_Character_BP_C" },
  { name: "Baryonyx", tag: "Baryonyx", className: "Baryonyx_Character_BP_C" },
  { name: "Basilosaurus", tag: "Basilosaurus", className: "Basilosaurus_Character_BP_C" },
  { name: "Manta", tag: "Manta", className: "Manta_Character_BP_C" },
  { name: "Sabertooth", tag: "Saber", className: "Saber_Character_BP_C" },
  { name: "Direwolf", tag: "Direwolf", className: "Direwolf_Character_BP_C" },
  { name: "Woolly Mammoth", tag: "Mammoth", className: "Mammoth_Character_BP_C" },
  { name: "Megatherium", tag: "Megatherium", className: "Megatherium_Character_BP_C" },
  { name: "Castoroides (Beaver)", tag: "Beaver", className: "Beaver_Character_BP_C" },
  { name: "Gigantopithecus", tag: "Bigfoot", className: "Bigfoot_Character_BP_C" },
  { name: "Procoptodon", tag: "Procoptodon", className: "Procoptodon_Character_BP_C" },
  { name: "Equus", tag: "Equus", className: "Equus_Character_BP_C" },
  { name: "Megaloceros", tag: "Stag", className: "Stag_Character_BP_C" },
  { name: "Phiomia", tag: "Phiomia", className: "Phiomia_Character_BP_C" },
  { name: "Dodo", tag: "Dodo", className: "Dodo_Character_BP_C" },
  { name: "Dilophosaur", tag: "Dilo", className: "Dilo_Character_BP_C" },
  { name: "Compy", tag: "Compy", className: "Compy_Character_BP_C" },
  { name: "Gallimimus", tag: "Galli", className: "Galli_Character_BP_C" },
  { name: "Pachy", tag: "Pachy", className: "Pachy_Character_BP_C" },
  { name: "Iguanodon", tag: "Iguanodon", className: "Iguanodon_Character_BP_C" },
  { name: "Carbonemys (Turtle)", tag: "Turtle", className: "Turtle_Character_BP_C" },
  { name: "Beelzebufo (Frog)", tag: "Toad", className: "Toad_Character_BP_C" },
  { name: "Kaprosuchus", tag: "Kaprosuchus", className: "Kaprosuchus_Character_BP_C" },
  { name: "Pulmonoscorpius (Scorpion)", tag: "Scorpion", className: "Scorpion_Character_BP_C" },
  { name: "Araneo (Spider)", tag: "Spider", className: "SpiderS_Character_BP_C" },
  { name: "Arthropluera", tag: "Arthro", className: "Arthro_Character_BP_C" },
  { name: "Mantis", tag: "Mantis", className: "Mantis_Character_BP_C" },
  { name: "Yutyrannus", tag: "Yutyrannus", className: "Yutyrannus_Character_BP_C" },
  { name: "Woolly Rhino", tag: "Rhino", className: "Rhino_Character_BP_C" },
  { name: "Daeodon", tag: "Daeodon", className: "Daeodon_Character_BP_C" },
  { name: "Thylacoleo", tag: "Thylacoleo", className: "Thylacoleo_Character_BP_C" },
  { name: "Megalania", tag: "Megalania", className: "Megalania_Character_BP_C" },
  { name: "Terror Bird", tag: "TerrorBird", className: "TerrorBird_Character_BP_C" },
  { name: "Ovis (Sheep)", tag: "Sheep", className: "Sheep_Character_BP_C" },
  { name: "Coelacanth", tag: "Coel", className: "Coel_Character_BP_C" },
  { name: "Lystrosaurus", tag: "Lystro", className: "Lystro_Character_BP_C" },
  { name: "Moschops", tag: "Moschops", className: "Moschops_Character_BP_C" },
  { name: "Titanosaur", tag: "Titanosaur", className: "Titanosaur_Character_BP_C" },
];
